services:
  - type: web
    name: phishing-url-detector
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
